const state={items:JSON.parse(localStorage.getItem('fefo_catalog_admin_items')||'[]')};
const $=s=>document.querySelector(s); const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const audio=['wav','mp3','flac','ogg','m4a']; const face=['png','jpg','jpeg','bmp','raw','bin']; const video=['mp4','mkv','avi','mov','webm'];
function infer(file){const ext=file.name.split('.').pop().toLowerCase();let tipo=audio.includes(ext)?'audio':face.includes(ext)?'face':video.includes(ext)?'video':'audio';const parts=file.name.replace(/\.[^.]+$/,'').split(/\s+-\s+/).map(x=>x.trim()).filter(Boolean);let menu=tipo==='audio'?'Jukebox do Fefo':tipo==='face'?'Faces':'Vídeos',submenu='',titulo=parts.at(-1)||file.name;if(parts.length>=2){menu=parts[0];titulo=parts.at(-1);submenu=parts.length>2?parts.slice(1,-1).join(' > '):''}return {arquivo_origem:file.name,titulo,menu_principal:menu,submenu,tipo,extensao:ext,publicar:'Sim',observacoes:'Cadastrado pelo administrador do catálogo',_file:file}};
function render(){const list=$('#list');$('#count').textContent=`${state.items.length} ${state.items.length===1?'item':'itens'}`;$('#empty').hidden=state.items.length>0;list.innerHTML=state.items.map((x,i)=>`<article class="item" data-i="${i}"><div class="file">${esc(x.arquivo_origem)} <small>· ${esc(x.extensao.toUpperCase())}</small></div><div class="field"><label>Título no app</label><input data-k="titulo" value="${esc(x.titulo)}"></div><div class="field"><label>Menu principal</label><input data-k="menu_principal" value="${esc(x.menu_principal)}"></div><div class="field"><label>Submenu</label><input data-k="submenu" value="${esc(x.submenu)}"></div><div class="field"><label>Tipo</label><select data-k="tipo"><option ${x.tipo==='audio'?'selected':''}>audio</option><option ${x.tipo==='face'?'selected':''}>face</option><option ${x.tipo==='video'?'selected':''}>video</option></select></div><div class="field"><label>Observações</label><input data-k="observacoes" value="${esc(x.observacoes)}"></div><label class="check"><input type="checkbox" data-k="publicar" ${x.publicar==='Sim'?'checked':''}> Publicar este item</label></article>`).join('');list.querySelectorAll('[data-k]').forEach(el=>el.addEventListener('input',()=>{const item=state.items[el.closest('.item').dataset.i];item[el.dataset.k]=el.type==='checkbox'?(el.checked?'Sim':'Não'):el.value;persist()}))}
function persist(){localStorage.setItem('fefo_catalog_admin_items',JSON.stringify(state.items.map(({_file,...x})=>x)))}
function add(files){[...files].forEach(file=>{if(!state.items.some(x=>x.arquivo_origem===file.name&&x._file?.size===file.size))state.items.push({...infer(file),_file:file})});persist();render();notice(`${files.length} arquivo(s) analisado(s). Revise os dados antes de salvar.`)}
function notice(text,type=''){const s=$('#status');s.textContent=text;s.className=`status ${type}`}
function csv(){const cols=['arquivo_origem','titulo','menu_principal','submenu','tipo','extensao','publicar','observacoes'];return '\ufeff'+[cols,...state.items.map(x=>cols.map(k=>`"${String(x[k]||'').replaceAll('"','""')}"`))].map(r=>r.join(';')).join('\n')}
function download(name,data,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
$('#files').addEventListener('change',e=>add(e.target.files));const drop=$('#drop');['dragenter','dragover'].forEach(e=>drop.addEventListener(e,x=>{x.preventDefault();drop.classList.add('over')}));['dragleave','drop'].forEach(e=>drop.addEventListener(e,x=>{x.preventDefault();drop.classList.remove('over')}));drop.addEventListener('drop',e=>add(e.dataTransfer.files));
$('#clear').addEventListener('click',()=>{state.items.length=0;persist();render();notice('Novos itens removidos da tela. O catálogo publicado não foi alterado.')});$('#export').addEventListener('click',()=>{if(!state.items.length)return notice('Adicione ao menos um arquivo antes de exportar.','error');download('Catalogo_Online_Planilha.csv',csv(),'text/csv;charset=utf-8');download('catalog-data.json',JSON.stringify({schema:1,generatedAt:new Date().toISOString(),items:state.items.map(({_file,...x})=>x)},null,2),'application/json');notice('Cadastro baixado. Agora salve os arquivos no projeto e processe a atualização.','ok')});
$('#save-folder').addEventListener('click',async()=>{if(!state.items.length)return notice('Adicione ao menos um arquivo antes de salvar.','error');if(!window.showDirectoryPicker)return notice('Seu navegador não permite salvar diretamente. Use “Baixar cadastro”.','error');try{const root=await showDirectoryPicker();const inbox=await root.getDirectoryHandle('FEFO_novos_conteudos',{create:true});const folders={audio:'audio',face:'faces',video:'video'};const handles={};for(const k of Object.values(folders))handles[k]=await inbox.getDirectoryHandle(k,{create:true});for(const x of state.items){if(!x._file)continue;const h=await handles[folders[x.tipo]];const f=await h.getFileHandle(x.arquivo_origem,{create:true});const w=await f.createWritable();await w.write(x._file);await w.close()}const cf=await inbox.getFileHandle('Catalogo_Online_Planilha.csv',{create:true});const cw=await cf.createWritable();await cw.write(csv());await cw.close();notice('Arquivos e metadados salvos no projeto. O próximo passo é processar e publicar.','ok')}catch(e){notice('Salvamento cancelado ou sem acesso à pasta escolhida.','error')}});render();
