(() => {
  let fileInput = document.querySelector('#audio-editor-file');
  if (!fileInput) {
    const host = document.querySelector('.import-card');
    if (!host) return;
    host.insertAdjacentHTML('afterend', `<section class="card audio-editor-card"><div class="audio-editor"><div class="editor-topbar"><div class="editor-tools"><span class="editor-tool active">✂ <b>Aparar</b><i></i></span><span class="editor-tool">🔊</span><span class="editor-tool">↶</span><span class="editor-tool">▥</span><span class="editor-tool">☷</span></div><button id="audio-editor-reset" class="editor-reset" type="button">↶ Redefinir</button><button class="editor-close" type="button" aria-label="Fechar editor">×</button></div><div class="editor-file-row"><label class="editor-file-button">Escolher áudio<input id="audio-editor-file" class="editor-file" type="file" accept="audio/*"></label><span id="audio-editor-file-name">Nenhum arquivo selecionado</span></div><canvas id="audio-editor-waveform" aria-label="Forma de onda do áudio"></canvas><audio id="audio-editor-preview" hidden></audio><div class="editor-controls"><label>Início <output id="audio-editor-start-value">0.00s</output><input id="audio-editor-start" type="range" min="0" max="1" step="0.01" value="0" disabled></label><label>Fim <output id="audio-editor-end-value">0.00s</output><input id="audio-editor-end" type="range" min="0" max="1" step="0.01" value="1" disabled></label><label>Zoom <output id="audio-editor-zoom-value">1x</output><input id="audio-editor-zoom" type="range" min="1" max="20" step="1" value="1" disabled></label><label>Fade in <output id="audio-editor-fade-in-value">0s</output><input id="audio-editor-fade-in" type="range" min="0" max="10" step="0.1" value="0"></label><label>Fade out <output id="audio-editor-fade-out-value">0s</output><input id="audio-editor-fade-out" type="range" min="0" max="10" step="0.1" value="0"></label></div><div class="editor-bottom"><button id="audio-editor-play" class="editor-play" type="button" disabled>▶</button><button id="audio-editor-fade-toggle" class="editor-icon-button" type="button" aria-label="Ativar fade">⌁</button><div class="editor-time-box"><label>Início <input id="audio-editor-start-number" type="number" min="0" step="0.1" value="0" disabled></label><label>Fim <input id="audio-editor-end-number" type="number" min="0" step="0.1" value="0" disabled></label></div><div class="editor-spacer"></div><select id="audio-editor-format" class="editor-format"><option value="wav">wav</option></select><button id="audio-editor-save" class="editor-save" type="button" disabled>Guardar</button></div><div class="editor-status" id="audio-editor-status" role="status">Escolha um áudio para começar.</div></div></section>`);
    fileInput = document.querySelector('#audio-editor-file');
  }
  const canvas = document.querySelector('#audio-editor-waveform'), audio = document.querySelector('#audio-editor-preview');
  const start = document.querySelector('#audio-editor-start'), end = document.querySelector('#audio-editor-end'), zoom = document.querySelector('#audio-editor-zoom');
  const startNumber = document.querySelector('#audio-editor-start-number'), endNumber = document.querySelector('#audio-editor-end-number');
  const startOut = document.querySelector('#audio-editor-start-value'), endOut = document.querySelector('#audio-editor-end-value'), zoomOut = document.querySelector('#audio-editor-zoom-value');
  const fadeIn = document.querySelector('#audio-editor-fade-in'), fadeOut = document.querySelector('#audio-editor-fade-out'), fadeToggle = document.querySelector('#audio-editor-fade-toggle');
  const fadeInOut = document.querySelector('#audio-editor-fade-in-value'), fadeOutOut = document.querySelector('#audio-editor-fade-out-value');
  const save = document.querySelector('#audio-editor-save'), play = document.querySelector('#audio-editor-play'), reset = document.querySelector('#audio-editor-reset'), status = document.querySelector('#audio-editor-status'), fileName = document.querySelector('#audio-editor-file-name');
  let sourceFile = null, buffer = null, dragging = null, animationFrame = 0, fadeEnabled = false;
  const fmt = value => `${Number(value).toFixed(2)}s`;
  const setStatus = (message, kind = '') => { status.textContent = message; status.className = `editor-status ${kind}`; };
  const view = () => { const duration = buffer.duration, span = duration / Number(zoom.value), center = (Number(start.value) + Number(end.value)) / 2, from = Math.max(0, Math.min(duration - span, center - span / 2)); return [from, from + span]; };
  const draw = () => {
    if (!buffer) return;
    const rect = canvas.getBoundingClientRect(), ratio = window.devicePixelRatio || 1; canvas.width = Math.max(1, Math.floor(rect.width * ratio)); canvas.height = Math.max(1, Math.floor(rect.height * ratio));
    const ctx = canvas.getContext('2d'), width = rect.width, height = rect.height; ctx.scale(ratio, ratio); ctx.fillStyle = '#123f6d'; ctx.fillRect(0, 0, width, height);
    const [viewFrom, viewTo] = view(), data = buffer.getChannelData(0), first = Math.floor(viewFrom * buffer.sampleRate), last = Math.min(data.length, Math.ceil(viewTo * buffer.sampleRate)), step = Math.max(1, Math.ceil((last - first) / width));
    ctx.strokeStyle = '#12e6b0'; ctx.lineWidth = 1; ctx.beginPath();
    for (let x = 0; x < width; x++) { const from = first + x * step, to = Math.min(last, from + step); let min = 1, max = -1; for (let i = from; i < to; i++) { min = Math.min(min, data[i]); max = Math.max(max, data[i]); } ctx.moveTo(x, (1 + min) * height / 2); ctx.lineTo(x, (1 + max) * height / 2); }
    ctx.stroke();
    const sx = (Number(start.value) - viewFrom) / (viewTo - viewFrom) * width, ex = (Number(end.value) - viewFrom) / (viewTo - viewFrom) * width; ctx.fillStyle = '#071d3988'; if (sx > 0) ctx.fillRect(0, 0, sx, height); if (ex < width) ctx.fillRect(ex, 0, width - ex, height); ctx.fillStyle = '#13dca055'; ctx.fillRect(Math.max(0, sx), 0, Math.max(0, ex - sx), height);
    [sx, ex].forEach((x, i) => { ctx.strokeStyle = i ? '#19d7ee' : '#19d7ee'; ctx.lineWidth = 8; ctx.beginPath(); ctx.moveTo(x, 0); ctx.lineTo(x, height); ctx.stroke(); ctx.fillStyle = '#19d7ee'; ctx.beginPath(); ctx.moveTo(x - 7, 0); ctx.lineTo(x + 7, 0); ctx.lineTo(x, 13); ctx.closePath(); ctx.fill(); });
    if (!audio.paused && audio.currentTime >= viewFrom && audio.currentTime <= viewTo) { const px = (audio.currentTime - viewFrom) / (viewTo - viewFrom) * width; ctx.strokeStyle = '#ffffff'; ctx.lineWidth = 1; ctx.beginPath(); ctx.moveTo(px, 0); ctx.lineTo(px, height); ctx.stroke(); ctx.fillStyle = '#ffffff'; ctx.beginPath(); ctx.moveTo(px - 5, height); ctx.lineTo(px + 5, height); ctx.lineTo(px, height - 10); ctx.closePath(); ctx.fill(); }
  };
  const sync = () => { if (!buffer) return; if (Number(start.value) >= Number(end.value)) { if (document.activeElement === start || document.activeElement === startNumber) start.value = Math.max(0, Number(end.value) - .01); else end.value = Math.min(buffer.duration, Number(start.value) + .01); } startNumber.value = start.value; endNumber.value = end.value; startOut.textContent = fmt(start.value); endOut.textContent = fmt(end.value); zoomOut.textContent = `${zoom.value}x`; fadeInOut.textContent = `${Number(fadeIn.value).toFixed(1)}s`; fadeOutOut.textContent = `${Number(fadeOut.value).toFixed(1)}s`; if (!audio.paused && (audio.currentTime < Number(start.value) || audio.currentTime >= Number(end.value))) audio.currentTime = Number(start.value); draw(); };
  const pointerTime = event => { const rect = canvas.getBoundingClientRect(), [from, to] = view(); return Math.max(from, Math.min(to, from + ((event.clientX - rect.left) / rect.width) * (to - from))); };
  canvas.addEventListener('pointerdown', event => { if (!buffer) return; const rect = canvas.getBoundingClientRect(), [from, to] = view(), x = event.clientX - rect.left, sx = (Number(start.value) - from) / (to - from) * rect.width, ex = (Number(end.value) - from) / (to - from) * rect.width; dragging = Math.abs(x - sx) <= Math.abs(x - ex) ? 'start' : 'end'; canvas.setPointerCapture(event.pointerId); });
  canvas.addEventListener('pointermove', event => { if (!dragging) return; const value = pointerTime(event); if (dragging === 'start') start.value = Math.min(value, Number(end.value) - .01); else end.value = Math.max(value, Number(start.value) + .01); sync(); });
  canvas.addEventListener('pointerup', () => { dragging = null; });
  const encodeWav = (data, sampleRate) => { const bytes = new ArrayBuffer(44 + data.length * 2), view = new DataView(bytes), write = (offset, text) => [...text].forEach((c, i) => view.setUint8(offset + i, c.charCodeAt(0))); write(0, 'RIFF'); view.setUint32(4, 36 + data.length * 2, true); write(8, 'WAVE'); write(12, 'fmt '); view.setUint32(16, 16, true); view.setUint16(20, 1, true); view.setUint16(22, 1, true); view.setUint32(24, sampleRate, true); view.setUint32(28, sampleRate * 2, true); view.setUint16(32, 2, true); view.setUint16(34, 16, true); write(36, 'data'); view.setUint32(40, data.length * 2, true); for (let i = 0; i < data.length; i++) view.setInt16(44 + i * 2, Math.max(-1, Math.min(1, data[i])) * 0x7fff, true); return new Blob([bytes], {type:'audio/wav'}); };
  const animate = () => { draw(); if (!audio.paused) animationFrame = requestAnimationFrame(animate); };
  const setPlaying = value => { play.textContent = value ? '❚❚' : '▶'; play.classList.toggle('playing', value); };
  audio.addEventListener('play', () => { if (buffer && (audio.currentTime < Number(start.value) || audio.currentTime >= Number(end.value))) audio.currentTime = Number(start.value); cancelAnimationFrame(animationFrame); animationFrame = requestAnimationFrame(animate); setPlaying(true); });
  audio.addEventListener('pause', () => { cancelAnimationFrame(animationFrame); setPlaying(false); draw(); });
  audio.addEventListener('timeupdate', () => { if (buffer && audio.currentTime >= Number(end.value)) { audio.pause(); audio.currentTime = Number(start.value); setStatus(`Prévia: ${fmt(start.value)} até ${fmt(end.value)}.`); } });
  audio.addEventListener('seeking', () => { if (buffer && audio.currentTime < Number(start.value)) audio.currentTime = Number(start.value); if (buffer && audio.currentTime > Number(end.value)) audio.currentTime = Number(end.value); });
  play.addEventListener('click', () => { if (!buffer) return; if (audio.paused) audio.play(); else audio.pause(); });
  const setFromNumber = (input, target) => { if (!buffer) return; target.value = Math.max(0, Math.min(buffer.duration, Number(input.value))); sync(); };
  start.addEventListener('input', sync); end.addEventListener('input', sync); zoom.addEventListener('input', sync); startNumber.addEventListener('change', () => setFromNumber(startNumber, start)); endNumber.addEventListener('change', () => setFromNumber(endNumber, end));
  [fadeIn, fadeOut].forEach(input => input.addEventListener('input', sync));
  fadeToggle.addEventListener('click', () => { fadeEnabled = !fadeEnabled; fadeToggle.classList.toggle('active', fadeEnabled); if (!fadeEnabled) { fadeIn.value = 0; fadeOut.value = 0; } sync(); });
  reset.addEventListener('click', () => { if (!buffer) return; start.value = 0; end.value = buffer.duration; zoom.value = 1; fadeIn.value = fadeOut.value = 0; audio.pause(); audio.currentTime = 0; sync(); setStatus(`Seleção redefinida: áudio completo (${fmt(buffer.duration)}).`); });
  fileInput.addEventListener('change', async () => { sourceFile = fileInput.files[0]; if (!sourceFile) return; try { buffer = await new AudioContext().decodeAudioData(await sourceFile.arrayBuffer()); start.max = end.max = buffer.duration; start.value = 0; end.value = buffer.duration; zoom.disabled = start.disabled = end.disabled = false; startNumber.disabled = endNumber.disabled = false; play.disabled = false; fadeIn.max = fadeOut.max = Math.min(10, buffer.duration / 2); audio.src = URL.createObjectURL(sourceFile); fileName.textContent = sourceFile.name; audio.hidden = false; save.disabled = false; sync(); setStatus('Arraste as barras azuis para definir o trecho.'); } catch { setStatus('Não foi possível ler este áudio.', 'error'); } });
  save.addEventListener('click', () => { if (!buffer || !sourceFile) return; const rate = buffer.sampleRate, from = Math.floor(Number(start.value) * rate), to = Math.floor(Number(end.value) * rate), result = new Float32Array(to - from), original = buffer.getChannelData(0), inSamples = fadeEnabled ? Math.floor(Number(fadeIn.value) * rate) : 0, outSamples = fadeEnabled ? Math.floor(Number(fadeOut.value) * rate) : 0; for (let i = 0; i < result.length; i++) { let gain = 1; if (inSamples && i < inSamples) gain *= i / inSamples; if (outSamples && i >= result.length - outSamples) gain *= (result.length - i) / outSamples; result[i] = original[from + i] * gain; } const base = sourceFile.name.replace(/\.[^.]+$/, '') || 'audio-editado', edited = new File([encodeWav(result, rate)], `${base}-editado.wav`, {type:'audio/wav'}), target = document.querySelector('#files'), transfer = new DataTransfer(); transfer.items.add(edited); target.files = transfer.files; target.dispatchEvent(new Event('change', {bubbles:true})); setStatus(`✓ ${edited.name} salvo para o catálogo. O original não será enviado.`, 'ok'); fileInput.value = ''; sourceFile = null; buffer = null; audio.pause(); audio.hidden = true; save.disabled = play.disabled = true; });
})();
