org.gradle.jvmargs=-Xmx1024M -XX:MaxMetaspaceSize=384M -Dfile.encoding=UTF-8 -XX:+UseSerialGC
org.gradle.workers.max=2
org.gradle.parallel=false
org.gradle.daemon=false
kotlin.daemon.jvm.options=-Xmx512M
android.useAndroidX=true
kotlin.incremental=false
android.enableJetifier=false
android.suppressUnsupportedCompileSdkWarning=31
