[platformio]
default_envs = led_core2
core_dir = ../../.platformio

[env:led_core2]
platform = espressif32 @ 7.0.1
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
lib_deps =
    adafruit/Adafruit NeoPixel @ 1.15.2
build_unflags =
    -std=gnu++11
build_flags =
    -std=gnu++17
